@startuml

package GameWindow {
    class GameWindowManager {
        - int frame_rate
        - string game_window_title
        - int game_window_width
        - int game_window_height
        - sf::RenderWindow* game_window
        - sf::VideoMode video_mode
        - sf::Color window_color
        - void initialize()
        - sf::RenderWindow* createGameWindow()
        - void setFrameRate(int)
        - void configureVideoMode()
        - void onDestroy()
        + GameWindowManager()
        + ~GameWindowManager()
        + bool isGameWindowOpen()
        + sf::RenderWindow* getGameWindow()
        + void update()
        + void render()
    }
}

package Event {
    enum MouseButtonState {
        PRESSED
        HELD
        RELEASED
    }

    class EventPollingManager {
        - sf::Event game_event
        - sf::RenderWindow* game_window
        - MouseButtonState left_mouse_button_state
        - MouseButtonState right_mouse_button_state
        - void initializeVariables(sf::RenderWindow*)
        - void updateMouseButtonState(MouseButtonState&, sf::Mouse::Button)
        - bool hasQuitGame()
        - bool isKeyboardEvent()
        - bool isGameWindowOpen()
        - bool gameWindowWasClosed()
        + EventPollingManager(sf::RenderWindow*)
        + ~EventPollingManager()
        + void processEvents()
        + void update()
        + bool pressedEscapeKey()
        + bool pressedLeftMouseButton()
        + bool pressedRightMouseButton()
        + sf::Vector2i getMousePosition()
    }
    EventPollingManager ..> MouseButtonState
}

package UI {
    class SplashScreenManager {
        - sf::RenderWindow* game_window
        - sf::Texture logo_texture
        - sf::Sprite logo_sprite
        - float logo_width
        - float logo_height
        - float logo_animation_duration
        - string logo_texture_path
        - float elapsed_time
        - void initialize()
        - sf::Vector2f getLogoPosition()
        - void drawLogo()
        + SplashScreenManager(sf::RenderWindow*)
        + ~SplashScreenManager()
        + void update()
        + void render()
    }
}

package UIElements {
    class Button {
        - sf::Sprite buttonSprite
        - sf::Texture button_texture
        - void initialize(string, sf::Vector2f, float, float)
        + Button(string, sf::Vector2f, float, float)
        + void setTextureRect(sf::IntRect)
        + void render(sf::RenderWindow&)
    }
}

package Gameplay {
    enum CellState {
        HIDDEN
        OPEN
        FLAGGED
    }

    enum CellType {
        EMPTY
        ONE
        TWO
        THREE
        FOUR
        FIVE
        SIX
        SEVEN
        EIGHT
        MINE
    }

    class Cell {
        - float cell_top_offset
        - float cell_left_offset
        - CellState current_cell_state
        - CellType cell_type
        - sf::Vector2i position
        - int tile_size
        - int slice_count
        - string cell_texture_path
        - UIElements::Button* cell_button
        - void initialize(float, float, sf::Vector2i)
        - sf::Vector2f getCellScreenPosition(float, float)
        + Cell(float, float, sf::Vector2i)
        + ~Cell()
        + CellState getCellState()
        + void setCellState(CellState)
        + CellType getCellType()
        + void setCellType(CellType)
        + void setCellTexture()
        + void render(sf::RenderWindow&)
    }

    class Board {
        - Cell* cell
        - float boardWidth
        - float boardHeight
        - float boardPosition
        - {static} int numberOfRows
        - {static} int numberOfColumns
        - float horizontalCellPadding
        - float verticalCellPadding
        - string boardTexturePath
        - sf::Texture boardTexture
        - sf::Sprite boardSprite
        - void initializeBoardImage()
        - void initialize()
        - void createBoard()
        - float getCellWidthInBoard()
        - float getCellHeightInBoard()
        + Board()
        + ~Board()
        + void render(sf::RenderWindow&)
    }

    class GameplayManager {
        - Board* board
        - float background_alpha
        - sf::Texture background_texture
        - sf::Sprite background_sprite
        - string background_texture_path
        - void initialize()
        - void initializeVariables()
        - void initializeBackground()
        + GameplayManager()
        + ~GameplayManager()
        + void render(sf::RenderWindow&)
    }
    GameplayManager *-- Board
    Board *-- Cell
    Cell *-- UIElements.Button
    Cell ..> CellState
    Cell ..> CellType
}

package Sound {
    enum SoundType {
        BUTTON_CLICK
        FLAG
        EXPLOSION
        GAME_WON
    }

    class SoundManager {
        - {static} sf::Music backgroundMusic
        - {static} sf::SoundBuffer bufferButtonClick
        - {static} sf::SoundBuffer bufferFlagSound
        - {static} sf::SoundBuffer bufferExplosion
        - {static} sf::SoundBuffer bufferGameWon
        - {static} sf::Sound soundEffect
        - {static} float backgroundMusicVolume
        - {static} string button_click_path
        - {static} string flag_sound_path
        - {static} string explosion_sound_path
        - {static} string game_won_sound_path
        - {static} string background_path
        - {static} void LoadBackgroundMusicFromFile()
        - {static} void LoadSoundFromFile()
        + {static} void Initialize()
        + {static} void PlaySound(SoundType)
        + {static} void PlayBackgroundMusic()
    }
    SoundManager ..> SoundType
}

package Time {
    class TimeManager {
        - {static} std::chrono::time_point previous_time
        - {static} float delta_time
        - {static} void updateDeltaTime()
        - {static} float calculateDeltaTime()
        - {static} void updatePreviousTime()
        + {static} void initialize()
        + {static} void update()
        + {static} float getDeltaTime()
    }
}

class GameLoop {
    - GameWindow::GameWindowManager* window_manager
    - Event::EventPollingManager* event_manager
    - sf::RenderWindow* game_window
    - UI::SplashScreenManager* splash_screen_manager
    - Gameplay::GameplayManager* gameplay_manager
    - {static} GameState current_state
    - void initialize()
    - void update()
    - void render()
    + GameLoop()
    + ~GameLoop()
    + void run()
    + {static} void setGameState(GameState)
}

enum GameState {
    SPLASH_SCREEN
    MAIN_MENU
    GAMEPLAY
    EXIT
}

GameLoop *-- GameWindow.GameWindowManager : Composes
GameLoop *-- Event.EventPollingManager : Composes
GameLoop *-- UI.SplashScreenManager : Composes
GameLoop *-- Gameplay.GameplayManager : Composes
GameLoop ..> Sound.SoundManager : Uses
GameLoop ..> Time.TimeManager : Uses
GameLoop ..> GameState : Uses

@enduml
